### ISSUE TITLE
A Better Way to Save Things using localStorage instead of Cookies

### ISSUE THREAD

**Issue by MiroTech** [ezfe/tellraw#174]
So, as your website directly says:
"Saves may reset at any time, and depend on your browsers cookies. Do not rely on them for extended periods of time."
There is a very easier way to save things than using cookies. You could just use localStorage. The localStorage JavaScript object saves strings of text permanently, and is saved locally on the user's computer. Although you won't be able to spy on what commands people are generating anymore, it will be a more secure way to save people's JSON commands. Use localStorage instead!
For instance, if I wanted to save a JSON command, I would use JavaScript code like this:
localStorage[saveName] = command;
And to load it back later, you can easily just do this:
var variableName = localStorage[saveName];
variableName will then be an object with all the localStorage entries inside. Got it? If there's a reason you haven't already done all this using localStorage, could you please reply with an email?
Also, if you do decided to update the site to use this saving technique, please find a way to NOT reset all of everyone's JSON saves. I HATE it when it does that, as I have tons of commands already saved, and I use them often. Thank you!

**Comment by ezfe** [comment]
I use localStorage already. You can see the code for that here: https://github.com/ezfe/tellraw/blob/ac2e0d1ca912f93e3e3b298349bff258145a0861/js/tellraw.js#L434-L454

You might see `lsm` and think that's not localStorage, but it is. That is just a wrapper for `localStorage` that I use to prevent issues when `localStorage` doesn't exist or isn't useable.

However, I'm going to phase out the Saves option for just exporting it to a text document in the future because, as you said, I sometimes have to reset the localStorage for everybody. I try not to do this, and as of right now it hasn't been reset for a while.

**Comment by MiroTech** [comment]
Okay, thank you. :D
