### ISSUE TITLE
It doesnt work with this command

### ISSUE THREAD

**Issue by Eno4379** [ezfe/tellraw#276]
/give @p written_book{pages:["[\"\",{\"selector\":\"@e[type=!item,distance=0.1..]\"},{\"text\":\"(\"},{\"nbt\":\"CustomName\",\"entity\":\"@e[type=!item,distance=0.1..]\"},{\"text\":\")\"},{\"score\":{\"name\":\"@e[type=!item,distance=0.1..]\",\"objective\":\"other_health\"}}]"],title:"Checking",author:Magic}

{"jformat":5,"jobject":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"adb21e9b-ae78-41c2-9841-39cc3fcc90df","selector":"@e[type=!item,distance=0.1..]"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"fc0a9ab7-4b7a-4bfd-9cd9-47ce5d27dd9a","text":"("},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"1c6dead8-42d3-45b7-bc99-777d4a5f49b9","type":"1","nbt":"CustomName","storage":"@e[type=!item,distance=0.1..]"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"d84dcc60-370f-4238-88a1-85be5d2027d1","text":")"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"846b734a-78a9-49a3-8f4d-75bf3d5cedab","score_name":"@e[type=!item,distance=0.1..]","score_objective":"other_health","score_value":null}],"command":"/give @p written_book{pages:%s,title:\"Custom Book\",author:Player}","jtemplate":"book"}

**Comment by Eno4379** [comment]
my verison is 1.15.2

**Comment by Eno4379** [comment]
![image](https://user-images.githubusercontent.com/51233594/77917090-aa0b8d00-72cc-11ea-990b-b4a07d97746c.png)

**Comment by ezfe** [comment]
I can confirm I'm seeing this and I'll investigate this! Thanks

**Comment by ezfe** [comment]
Hi,

This is occuring because books cannot have selectors with multiple results. If you add limit=1 to all the queries, it should work:

{"jformat":5,"jobject":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"adb21e9b-ae78-41c2-9841-39cc3fcc90df","selector":"@e[type=!item,distance=0.1..,limit=1]"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"fc0a9ab7-4b7a-4bfd-9cd9-47ce5d27dd9a","text":"("},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"1c6dead8-42d3-45b7-bc99-777d4a5f49b9","type":"1","nbt":"CustomName","storage":"@e[type=!item,distance=0.1..,limit=1]"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"d84dcc60-370f-4238-88a1-85be5d2027d1","text":")"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"846b734a-78a9-49a3-8f4d-75bf3d5cedab","score_name":"@e[type=!item,distance=0.1..,limit=1]","score_objective":"other_health","score_value":null}],"command":"/give @p written_book{pages:%s,title:\"Custom Book\",author:Player}","jtemplate":"book"}

**Comment by Eno4379** [comment]
i am using 1.15.2 version

**Comment by Eno4379** [comment]
thx
