### ISSUE TITLE
Tellraw generator interjects random code making commands unusable.

### ISSUE THREAD

**Issue by ZachTheInsaneOne** [ezfe/tellraw#277]
I attempted to use your tellraw generator for a simple death message, and it gave me the following code:
`/tellraw @p ["",{"selector":"","insertion":"@a[scores={Death=1}]"},{"text":"","insertion":" fell off the map!"}]`

It put random "insertion" events and put the text I wanted in there, instead of in the "selector" or "text" sections. This results simply in a blank message displaying nothing at all. The correct command is:
`/tellraw @a [{"selector":"@a[scores={Death=1}]"},{"text":" fell off the map!"}]`

I am not sure why your generator is putting insertion events for every single piece of text, but it is making the program effectively useless. In addition to that, it also puts `"",` in front of the command, again for no reason. Please fix this.

**Comment by ezfe** [comment]
I'm not seeing insertion behaving incorrectly, what browser are you using? As for the `"",` at the front, this is intentional and is because Minecraft inherits the style of text from the first element. Without this, bold in the first element propagates to the rest of the elements (for example).

https://gfycat.com/milkyunhealthybullmastiff

**Comment by ezfe** [comment]
I'm closing this issue, since I haven't received a reply
