### ISSUE TITLE
Add clickEvent to signs please!

### ISSUE THREAD

**Issue by SeeksThree** [ezfe/tellraw#284]
Hello! I use your generators daily and I just wanted to suggest adding a clickEvent tag to your sign generator. Thank you for reading!

**Comment by ezfe** [comment]
Hi @SeeksThree,

The Syntax for Sign click events is different, since unfortunately one cannot have more than one click event per line on a sign. You can make this work pretty easily though:

Set the format to a non-sign format, so that the click events appear available. Set up your command, being sure to use just one entry for each line on the sign, with line breaks in between (if that line is clickable). Change it to a sign format and copy it into a text editor.

Each line of the sign is in a blob labeled Text1-4. This example just has a Text1. For each line that has a click event, remove the `[\"\",` at the beginning and the `]` at the end. It should now work:

Original:
```
/give @p oak_sign{BlockEntityTag:{Text1:"[\"\",{\"text\":\"Hello There\",\"color\":\"green\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/say Hello\"}}]",id:"Sign"}}
                                         ^^^^^^                                                                                                                   ^
```

Modified:
```
/give @p oak_sign{BlockEntityTag:{Text1:"{\"text\":\"Hello There\",\"color\":\"green\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/say Hello\"}}",id:"Sign"}}
```

Hope this makes sense, and I'll always keep sign click events in mind.

**Comment by ezfe** [comment]
Hi @SeeksThree , you might've seen my earlier comment–but I've deleted it, since I went ahead and made it possible to do this in the site directly. Only add a single entry for each line, but now you can do click events on signs.

**Comment by SeeksThree** [comment]
Wow! I really don't know how to thank you for doing this! God bless you!
